### ISSUE TITLE
No crafting recipe for the ender soul?

### ISSUE THREAD

**Issue by sldains** [apace100/heartbond#1]
I was testing this mod out to possibly add to my game but there doesn't appear to be a recipe to make the ender soul and I tried various combinations of the hearts and soul sand (just in case REI failed me) but couldn't get anything to work.

**Comment by apace100** [comment]
Hi! That's weird, haven't had any reports of it not working so far. Could you share a screenshot of what you tried? The recipe should work if you put two hearts and a soul sand into the crafting grid.
Also, please share a list of other installed mods if you can, and possibly also try it out on an installation with just Heartbond installed, to check for mod conflicts.

Thanks!

**Comment by sldains** [comment]
yeah, it must be a mod messing it up because I did just test it in a bare-bones pack and it was fine. T-T I'm running 119 mods in my main pack so now to begin the long process of sorting out conflicts.
